### ISSUE TITLE
how to calculate focal length of my cam, which is required as one of the parameter.

### ISSUE THREAD

**Issue by shubham-shahh** [by-sabbir/HeadPoseEstimation#1]

**Comment by by-sabbir** [comment]
The focal length is one of the intrinsic properties of a camera. We can estimate them using camera calibration. You can follow https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html
in this guide. There if you look at the camera matrix, you will find- fx=fy=focul_length.
